//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 06/04/2016 14:28:26
namespace AirVinyl.Model
{
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    public partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Person> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::AirVinyl.Model.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> _Friends;
        /// <summary>
        /// There are no comments for VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> VinylRecords
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._VinylRecords == null))
                {
                    this._VinylRecords = Context.CreateQuery<global::AirVinyl.Model.VinylRecord>(GetPath("VinylRecords"));
                }
                return this._VinylRecords;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> _VinylRecords;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PersonId")]
    public partial class Person : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personId">Initial value of PersonId.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="dateOfBirth">Initial value of DateOfBirth.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="numberOfRecordsOnWishList">Initial value of NumberOfRecordsOnWishList.</param>
        /// <param name="amountOfCashToSpend">Initial value of AmountOfCashToSpend.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Person CreatePerson(int personId, 
                    string firstName, 
                    string lastName, 
                    global::System.DateTimeOffset dateOfBirth, 
                    global::AirVinyl.Model.Gender gender, 
                    int numberOfRecordsOnWishList, 
                    decimal amountOfCashToSpend)
        {
            Person person = new Person();
            person.PersonId = personId;
            person.FirstName = firstName;
            person.LastName = lastName;
            person.DateOfBirth = dateOfBirth;
            person.Gender = gender;
            person.NumberOfRecordsOnWishList = numberOfRecordsOnWishList;
            person.AmountOfCashToSpend = amountOfCashToSpend;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int PersonId
        {
            get
            {
                return this._PersonId;
            }
            set
            {
                this.OnPersonIdChanging(value);
                this._PersonId = value;
                this.OnPersonIdChanged();
                this.OnPropertyChanged("PersonId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PersonId;
        partial void OnPersonIdChanging(int value);
        partial void OnPersonIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
                this.OnPropertyChanged("DateOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTimeOffset value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Gender Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Gender _Gender;
        partial void OnGenderChanging(global::AirVinyl.Model.Gender value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecordsOnWishList in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int NumberOfRecordsOnWishList
        {
            get
            {
                return this._NumberOfRecordsOnWishList;
            }
            set
            {
                this.OnNumberOfRecordsOnWishListChanging(value);
                this._NumberOfRecordsOnWishList = value;
                this.OnNumberOfRecordsOnWishListChanged();
                this.OnPropertyChanged("NumberOfRecordsOnWishList");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _NumberOfRecordsOnWishList;
        partial void OnNumberOfRecordsOnWishListChanging(int value);
        partial void OnNumberOfRecordsOnWishListChanged();
        /// <summary>
        /// There are no comments for Property AmountOfCashToSpend in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal AmountOfCashToSpend
        {
            get
            {
                return this._AmountOfCashToSpend;
            }
            set
            {
                this.OnAmountOfCashToSpendChanging(value);
                this._AmountOfCashToSpend = value;
                this.OnAmountOfCashToSpendChanged();
                this.OnPropertyChanged("AmountOfCashToSpend");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _AmountOfCashToSpend;
        partial void OnAmountOfCashToSpendChanging(decimal value);
        partial void OnAmountOfCashToSpendChanged();
        /// <summary>
        /// There are no comments for Property Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> Friends
        {
            get
            {
                return this._Friends;
            }
            set
            {
                this.OnFriendsChanging(value);
                this._Friends = value;
                this.OnFriendsChanged();
                this.OnPropertyChanged("Friends");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> _Friends = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFriendsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Person> value);
        partial void OnFriendsChanged();
        /// <summary>
        /// There are no comments for Property VinylRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> VinylRecords
        {
            get
            {
                return this._VinylRecords;
            }
            set
            {
                this.OnVinylRecordsChanging(value);
                this._VinylRecords = value;
                this.OnVinylRecordsChanged();
                this.OnPropertyChanged("VinylRecords");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> _VinylRecords = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnVinylRecordsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.VinylRecord> value);
        partial void OnVinylRecordsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RecordStoreSingle in the schema.
    /// </summary>
    public partial class RecordStoreSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RecordStore>
    {
        /// <summary>
        /// Initialize a new RecordStoreSingle object.
        /// </summary>
        public RecordStoreSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RecordStoreSingle object.
        /// </summary>
        public RecordStoreSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RecordStoreSingle object.
        /// </summary>
        public RecordStoreSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RecordStore> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> Ratings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Ratings == null))
                {
                    this._Ratings = Context.CreateQuery<global::AirVinyl.Model.Rating>(GetPath("Ratings"));
                }
                return this._Ratings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> _Ratings;
    }
    /// <summary>
    /// There are no comments for RecordStore in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RecordStoreId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("RecordStoreId")]
    public partial class RecordStore : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RecordStore object.
        /// </summary>
        /// <param name="recordStoreId">Initial value of RecordStoreId.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static RecordStore CreateRecordStore(int recordStoreId, string name)
        {
            RecordStore recordStore = new RecordStore();
            recordStore.RecordStoreId = recordStoreId;
            recordStore.Name = name;
            return recordStore;
        }
        /// <summary>
        /// There are no comments for Property RecordStoreId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int RecordStoreId
        {
            get
            {
                return this._RecordStoreId;
            }
            set
            {
                this.OnRecordStoreIdChanging(value);
                this._RecordStoreId = value;
                this.OnRecordStoreIdChanged();
                this.OnPropertyChanged("RecordStoreId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _RecordStoreId;
        partial void OnRecordStoreIdChanging(int value);
        partial void OnRecordStoreIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property StoreAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Address StoreAddress
        {
            get
            {
                return this._StoreAddress;
            }
            set
            {
                this.OnStoreAddressChanging(value);
                this._StoreAddress = value;
                this.OnStoreAddressChanged();
                this.OnPropertyChanged("StoreAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Address _StoreAddress;
        partial void OnStoreAddressChanging(global::AirVinyl.Model.Address value);
        partial void OnStoreAddressChanged();
        /// <summary>
        /// There are no comments for Property Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<string> Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this.OnTagsChanging(value);
                this._Tags = value;
                this.OnTagsChanged();
                this.OnPropertyChanged("Tags");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _Tags = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnTagsChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnTagsChanged();
        /// <summary>
        /// There are no comments for Property TagsAsString in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string TagsAsString
        {
            get
            {
                return this._TagsAsString;
            }
            set
            {
                this.OnTagsAsStringChanging(value);
                this._TagsAsString = value;
                this.OnTagsAsStringChanged();
                this.OnPropertyChanged("TagsAsString");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _TagsAsString;
        partial void OnTagsAsStringChanging(string value);
        partial void OnTagsAsStringChanged();
        /// <summary>
        /// There are no comments for Property Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Rating> Ratings
        {
            get
            {
                return this._Ratings;
            }
            set
            {
                this.OnRatingsChanging(value);
                this._Ratings = value;
                this.OnRatingsChanged();
                this.OnPropertyChanged("Ratings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Rating> _Ratings = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Rating>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRatingsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.Rating> value);
        partial void OnRatingsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for VinylRecordSingle in the schema.
    /// </summary>
    public partial class VinylRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VinylRecord>
    {
        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VinylRecordSingle object.
        /// </summary>
        public VinylRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VinylRecord> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PressingDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PressingDetailSingle PressingDetail
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PressingDetail == null))
                {
                    this._PressingDetail = new global::AirVinyl.Model.PressingDetailSingle(this.Context, GetPath("PressingDetail"));
                }
                return this._PressingDetail;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PressingDetailSingle _PressingDetail;
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PersonSingle Person
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Person == null))
                {
                    this._Person = new global::AirVinyl.Model.PersonSingle(this.Context, GetPath("Person"));
                }
                return this._Person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PersonSingle _Person;
        /// <summary>
        /// There are no comments for DynamicVinylRecordProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.DynamicProperty> DynamicVinylRecordProperties
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DynamicVinylRecordProperties == null))
                {
                    this._DynamicVinylRecordProperties = Context.CreateQuery<global::AirVinyl.Model.DynamicProperty>(GetPath("DynamicVinylRecordProperties"));
                }
                return this._DynamicVinylRecordProperties;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.DynamicProperty> _DynamicVinylRecordProperties;
    }
    /// <summary>
    /// There are no comments for VinylRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// VinylRecordId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("VinylRecordId")]
    public partial class VinylRecord : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VinylRecord object.
        /// </summary>
        /// <param name="vinylRecordId">Initial value of VinylRecordId.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="artist">Initial value of Artist.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static VinylRecord CreateVinylRecord(int vinylRecordId, string title, string artist)
        {
            VinylRecord vinylRecord = new VinylRecord();
            vinylRecord.VinylRecordId = vinylRecordId;
            vinylRecord.Title = title;
            vinylRecord.Artist = artist;
            return vinylRecord;
        }
        /// <summary>
        /// There are no comments for Property VinylRecordId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int VinylRecordId
        {
            get
            {
                return this._VinylRecordId;
            }
            set
            {
                this.OnVinylRecordIdChanging(value);
                this._VinylRecordId = value;
                this.OnVinylRecordIdChanged();
                this.OnPropertyChanged("VinylRecordId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _VinylRecordId;
        partial void OnVinylRecordIdChanging(int value);
        partial void OnVinylRecordIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Artist in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Artist
        {
            get
            {
                return this._Artist;
            }
            set
            {
                this.OnArtistChanging(value);
                this._Artist = value;
                this.OnArtistChanged();
                this.OnPropertyChanged("Artist");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Artist;
        partial void OnArtistChanging(string value);
        partial void OnArtistChanged();
        /// <summary>
        /// There are no comments for Property CatalogNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string CatalogNumber
        {
            get
            {
                return this._CatalogNumber;
            }
            set
            {
                this.OnCatalogNumberChanging(value);
                this._CatalogNumber = value;
                this.OnCatalogNumberChanged();
                this.OnPropertyChanged("CatalogNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CatalogNumber;
        partial void OnCatalogNumberChanging(string value);
        partial void OnCatalogNumberChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Year;
        partial void OnYearChanging(global::System.Nullable<int> value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property PressingDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PressingDetail PressingDetail
        {
            get
            {
                return this._PressingDetail;
            }
            set
            {
                this.OnPressingDetailChanging(value);
                this._PressingDetail = value;
                this.OnPressingDetailChanged();
                this.OnPropertyChanged("PressingDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PressingDetail _PressingDetail;
        partial void OnPressingDetailChanging(global::AirVinyl.Model.PressingDetail value);
        partial void OnPressingDetailChanged();
        /// <summary>
        /// There are no comments for Property Person in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Person Person
        {
            get
            {
                return this._Person;
            }
            set
            {
                this.OnPersonChanging(value);
                this._Person = value;
                this.OnPersonChanged();
                this.OnPropertyChanged("Person");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Person _Person;
        partial void OnPersonChanging(global::AirVinyl.Model.Person value);
        partial void OnPersonChanged();
        /// <summary>
        /// There are no comments for Property DynamicVinylRecordProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.DynamicProperty> DynamicVinylRecordProperties
        {
            get
            {
                return this._DynamicVinylRecordProperties;
            }
            set
            {
                this.OnDynamicVinylRecordPropertiesChanging(value);
                this._DynamicVinylRecordProperties = value;
                this.OnDynamicVinylRecordPropertiesChanged();
                this.OnPropertyChanged("DynamicVinylRecordProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.DynamicProperty> _DynamicVinylRecordProperties = new global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.DynamicProperty>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDynamicVinylRecordPropertiesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::AirVinyl.Model.DynamicProperty> value);
        partial void OnDynamicVinylRecordPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PressingDetailSingle in the schema.
    /// </summary>
    public partial class PressingDetailSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PressingDetail>
    {
        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PressingDetailSingle object.
        /// </summary>
        public PressingDetailSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PressingDetail> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PressingDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PressingDetailId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PressingDetailId")]
    public partial class PressingDetail : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PressingDetail object.
        /// </summary>
        /// <param name="pressingDetailId">Initial value of PressingDetailId.</param>
        /// <param name="grams">Initial value of Grams.</param>
        /// <param name="inches">Initial value of Inches.</param>
        /// <param name="description">Initial value of Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static PressingDetail CreatePressingDetail(int pressingDetailId, int grams, int inches, string description)
        {
            PressingDetail pressingDetail = new PressingDetail();
            pressingDetail.PressingDetailId = pressingDetailId;
            pressingDetail.Grams = grams;
            pressingDetail.Inches = inches;
            pressingDetail.Description = description;
            return pressingDetail;
        }
        /// <summary>
        /// There are no comments for Property PressingDetailId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int PressingDetailId
        {
            get
            {
                return this._PressingDetailId;
            }
            set
            {
                this.OnPressingDetailIdChanging(value);
                this._PressingDetailId = value;
                this.OnPressingDetailIdChanged();
                this.OnPropertyChanged("PressingDetailId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PressingDetailId;
        partial void OnPressingDetailIdChanging(int value);
        partial void OnPressingDetailIdChanged();
        /// <summary>
        /// There are no comments for Property Grams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Grams
        {
            get
            {
                return this._Grams;
            }
            set
            {
                this.OnGramsChanging(value);
                this._Grams = value;
                this.OnGramsChanged();
                this.OnPropertyChanged("Grams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Grams;
        partial void OnGramsChanging(int value);
        partial void OnGramsChanged();
        /// <summary>
        /// There are no comments for Property Inches in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Inches
        {
            get
            {
                return this._Inches;
            }
            set
            {
                this.OnInchesChanging(value);
                this._Inches = value;
                this.OnInchesChanged();
                this.OnPropertyChanged("Inches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Inches;
        partial void OnInchesChanging(int value);
        partial void OnInchesChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DynamicPropertySingle in the schema.
    /// </summary>
    public partial class DynamicPropertySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicProperty>
    {
        /// <summary>
        /// Initialize a new DynamicPropertySingle object.
        /// </summary>
        public DynamicPropertySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DynamicPropertySingle object.
        /// </summary>
        public DynamicPropertySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DynamicPropertySingle object.
        /// </summary>
        public DynamicPropertySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DynamicProperty> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for VinylRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.VinylRecordSingle VinylRecord
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._VinylRecord == null))
                {
                    this._VinylRecord = new global::AirVinyl.Model.VinylRecordSingle(this.Context, GetPath("VinylRecord"));
                }
                return this._VinylRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.VinylRecordSingle _VinylRecord;
    }
    /// <summary>
    /// There are no comments for DynamicProperty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Key
    /// VinylRecordId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Key", "VinylRecordId")]
    public partial class DynamicProperty : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DynamicProperty object.
        /// </summary>
        /// <param name="key">Initial value of Key.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static DynamicProperty CreateDynamicProperty(string key)
        {
            DynamicProperty dynamicProperty = new DynamicProperty();
            dynamicProperty.Key = key;
            return dynamicProperty;
        }
        /// <summary>
        /// There are no comments for Property Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Key
        {
            get
            {
                return this._Key;
            }
            set
            {
                this.OnKeyChanging(value);
                this._Key = value;
                this.OnKeyChanged();
                this.OnPropertyChanged("Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Key;
        partial void OnKeyChanging(string value);
        partial void OnKeyChanged();
        /// <summary>
        /// There are no comments for Property SerializedValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string SerializedValue
        {
            get
            {
                return this._SerializedValue;
            }
            set
            {
                this.OnSerializedValueChanging(value);
                this._SerializedValue = value;
                this.OnSerializedValueChanged();
                this.OnPropertyChanged("SerializedValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SerializedValue;
        partial void OnSerializedValueChanging(string value);
        partial void OnSerializedValueChanged();
        /// <summary>
        /// There are no comments for Property VinylRecordId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> VinylRecordId
        {
            get
            {
                return this._VinylRecordId;
            }
            set
            {
                this.OnVinylRecordIdChanging(value);
                this._VinylRecordId = value;
                this.OnVinylRecordIdChanged();
                this.OnPropertyChanged("VinylRecordId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _VinylRecordId;
        partial void OnVinylRecordIdChanging(global::System.Nullable<int> value);
        partial void OnVinylRecordIdChanged();
        /// <summary>
        /// There are no comments for Property VinylRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.VinylRecord VinylRecord
        {
            get
            {
                return this._VinylRecord;
            }
            set
            {
                this.OnVinylRecordChanging(value);
                this._VinylRecord = value;
                this.OnVinylRecordChanged();
                this.OnPropertyChanged("VinylRecord");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.VinylRecord _VinylRecord;
        partial void OnVinylRecordChanging(global::AirVinyl.Model.VinylRecord value);
        partial void OnVinylRecordChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Address in the schema.
    /// </summary>
    public partial class Address : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
                this.OnPropertyChanged("PostalCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RatingSingle in the schema.
    /// </summary>
    public partial class RatingSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Rating>
    {
        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RatingSingle object.
        /// </summary>
        public RatingSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Rating> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for RatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PersonSingle RatedBy
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RatedBy == null))
                {
                    this._RatedBy = new global::AirVinyl.Model.PersonSingle(this.Context, GetPath("RatedBy"));
                }
                return this._RatedBy;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PersonSingle _RatedBy;
    }
    /// <summary>
    /// There are no comments for Rating in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RatingId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("RatingId")]
    public partial class Rating : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="ratingId">Initial value of RatingId.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="ratedBy">Initial value of RatedBy.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Rating CreateRating(int ratingId, int value, global::AirVinyl.Model.Person ratedBy)
        {
            Rating rating = new Rating();
            rating.RatingId = ratingId;
            rating.Value = value;
            if ((ratedBy == null))
            {
                throw new global::System.ArgumentNullException("ratedBy");
            }
            rating.RatedBy = ratedBy;
            return rating;
        }
        /// <summary>
        /// There are no comments for Property RatingId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int RatingId
        {
            get
            {
                return this._RatingId;
            }
            set
            {
                this.OnRatingIdChanging(value);
                this._RatingId = value;
                this.OnRatingIdChanged();
                this.OnPropertyChanged("RatingId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _RatingId;
        partial void OnRatingIdChanging(int value);
        partial void OnRatingIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Value;
        partial void OnValueChanging(int value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property RatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.Person RatedBy
        {
            get
            {
                return this._RatedBy;
            }
            set
            {
                this.OnRatedByChanging(value);
                this._RatedBy = value;
                this.OnRatedByChanged();
                this.OnPropertyChanged("RatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.Person _RatedBy;
        partial void OnRatedByChanging(global::AirVinyl.Model.Person value);
        partial void OnRatedByChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SpecializedRecordStoreSingle in the schema.
    /// </summary>
    public partial class SpecializedRecordStoreSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SpecializedRecordStore>
    {
        /// <summary>
        /// Initialize a new SpecializedRecordStoreSingle object.
        /// </summary>
        public SpecializedRecordStoreSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SpecializedRecordStoreSingle object.
        /// </summary>
        public SpecializedRecordStoreSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SpecializedRecordStoreSingle object.
        /// </summary>
        public SpecializedRecordStoreSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<SpecializedRecordStore> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> Ratings
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Ratings == null))
                {
                    this._Ratings = Context.CreateQuery<global::AirVinyl.Model.Rating>(GetPath("Ratings"));
                }
                return this._Ratings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> _Ratings;
    }
    /// <summary>
    /// There are no comments for SpecializedRecordStore in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RecordStoreId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("RecordStoreId")]
    public partial class SpecializedRecordStore : RecordStore
    {
        /// <summary>
        /// Create a new SpecializedRecordStore object.
        /// </summary>
        /// <param name="recordStoreId">Initial value of RecordStoreId.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static SpecializedRecordStore CreateSpecializedRecordStore(int recordStoreId, string name)
        {
            SpecializedRecordStore specializedRecordStore = new SpecializedRecordStore();
            specializedRecordStore.RecordStoreId = recordStoreId;
            specializedRecordStore.Name = name;
            return specializedRecordStore;
        }
        /// <summary>
        /// There are no comments for Property Specialization in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Specialization
        {
            get
            {
                return this._Specialization;
            }
            set
            {
                this.OnSpecializationChanging(value);
                this._Specialization = value;
                this.OnSpecializationChanged();
                this.OnPropertyChanged("Specialization");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Specialization;
        partial void OnSpecializationChanging(string value);
        partial void OnSpecializationChanged();
    }
    /// <summary>
    /// There are no comments for Gender in the schema.
    /// </summary>
    public enum Gender
    {
        Female = 0,
        Male = 1,
        Other = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Person as global::AirVinyl.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Person as global::AirVinyl.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="personId">The value of personId</param>
        public static global::AirVinyl.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> source,
            int personId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PersonId", personId }
            };
            return new global::AirVinyl.Model.PersonSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.RecordStore as global::AirVinyl.Model.RecordStoreSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.RecordStoreSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.RecordStoreSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.RecordStore as global::AirVinyl.Model.RecordStoreSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="recordStoreId">The value of recordStoreId</param>
        public static global::AirVinyl.Model.RecordStoreSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> source,
            int recordStoreId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "RecordStoreId", recordStoreId }
            };
            return new global::AirVinyl.Model.RecordStoreSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.VinylRecord as global::AirVinyl.Model.VinylRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.VinylRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.VinylRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.VinylRecord as global::AirVinyl.Model.VinylRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="vinylRecordId">The value of vinylRecordId</param>
        public static global::AirVinyl.Model.VinylRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.VinylRecord> source,
            int vinylRecordId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "VinylRecordId", vinylRecordId }
            };
            return new global::AirVinyl.Model.VinylRecordSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.PressingDetail as global::AirVinyl.Model.PressingDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.PressingDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.PressingDetail> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.PressingDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.PressingDetail as global::AirVinyl.Model.PressingDetailSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pressingDetailId">The value of pressingDetailId</param>
        public static global::AirVinyl.Model.PressingDetailSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.PressingDetail> source,
            int pressingDetailId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PressingDetailId", pressingDetailId }
            };
            return new global::AirVinyl.Model.PressingDetailSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.DynamicProperty as global::AirVinyl.Model.DynamicPropertySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.DynamicPropertySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.DynamicProperty> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.DynamicPropertySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.DynamicProperty as global::AirVinyl.Model.DynamicPropertySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="key">The value of key</param>
        /// <param name="vinylRecordId">The value of vinylRecordId</param>
        public static global::AirVinyl.Model.DynamicPropertySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.DynamicProperty> source,
            string key, 
            global::System.Nullable<int> vinylRecordId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Key", key }, 
                { "VinylRecordId", vinylRecordId }
            };
            return new global::AirVinyl.Model.DynamicPropertySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Rating as global::AirVinyl.Model.RatingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.RatingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.RatingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.Rating as global::AirVinyl.Model.RatingSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="ratingId">The value of ratingId</param>
        public static global::AirVinyl.Model.RatingSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Rating> source,
            int ratingId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "RatingId", ratingId }
            };
            return new global::AirVinyl.Model.RatingSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.SpecializedRecordStore as global::AirVinyl.Model.SpecializedRecordStoreSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AirVinyl.Model.SpecializedRecordStoreSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.SpecializedRecordStore> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::AirVinyl.Model.SpecializedRecordStoreSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AirVinyl.Model.SpecializedRecordStore as global::AirVinyl.Model.SpecializedRecordStoreSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="recordStoreId">The value of recordStoreId</param>
        public static global::AirVinyl.Model.SpecializedRecordStoreSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.SpecializedRecordStore> source,
            int recordStoreId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "RecordStoreId", recordStoreId }
            };
            return new global::AirVinyl.Model.SpecializedRecordStoreSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::AirVinyl.Model.RecordStore to its derived type global::AirVinyl.Model.SpecializedRecordStore
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::AirVinyl.Model.SpecializedRecordStoreSingle CastToSpecializedRecordStore(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::AirVinyl.Model.RecordStore> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::AirVinyl.Model.SpecializedRecordStore> query = source.CastTo<global::AirVinyl.Model.SpecializedRecordStore>();
            return new global::AirVinyl.Model.SpecializedRecordStoreSingle(source.Context, query.GetPath(null));
        }
    }
}
namespace AirVinyl.Functions
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for IsHighRated in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<bool> IsHighRated(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::AirVinyl.Model.RecordStore> source, int minimumRating)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuerySingle<bool>("AirVinyl.Functions.IsHighRated", false, new global::Microsoft.OData.Client.UriOperationParameter("minimumRating", minimumRating));
        }
        /// <summary>
        /// There are no comments for AreRatedBy in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> AreRatedBy(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> source, global::System.Collections.Generic.ICollection<int> personIds)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuery<global::AirVinyl.Model.RecordStore>("AirVinyl.Functions.AreRatedBy", false, new global::Microsoft.OData.Client.UriOperationParameter("personIds", personIds));
        }
    }
}
namespace AirVinyl.Actions
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for Rate in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool> Rate(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::AirVinyl.Model.RecordStore> source, int rating, int personId)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool>(source.Context, source.AppendRequestUri("AirVinyl.Actions.Rate"), new global::Microsoft.OData.Client.BodyOperationParameter("rating", rating),
                    new global::Microsoft.OData.Client.BodyOperationParameter("personId", personId));
        }
        /// <summary>
        /// There are no comments for RemoveRatings in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool> RemoveRatings(this global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> source, int personId)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool>(source.Context, source.AppendRequestUri("AirVinyl.Actions.RemoveRatings"), new global::Microsoft.OData.Client.BodyOperationParameter("personId", personId));
        }
    }
}
namespace AirVinyl
{
    /// <summary>
    /// There are no comments for AirVinylContainer in the schema.
    /// </summary>
    public partial class AirVinylContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AirVinylContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public AirVinylContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<global::AirVinyl.Model.Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.Person> _People;
        /// <summary>
        /// There are no comments for RecordStores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> RecordStores
        {
            get
            {
                if ((this._RecordStores == null))
                {
                    this._RecordStores = base.CreateQuery<global::AirVinyl.Model.RecordStore>("RecordStores");
                }
                return this._RecordStores;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> _RecordStores;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPeople(global::AirVinyl.Model.Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for RecordStores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRecordStores(global::AirVinyl.Model.RecordStore recordStore)
        {
            base.AddObject("RecordStores", recordStore);
        }
        /// <summary>
        /// There are no comments for Tim in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::AirVinyl.Model.PersonSingle Tim
        {
            get
            {
                if ((this._Tim == null))
                {
                    this._Tim = new global::AirVinyl.Model.PersonSingle(this, "Tim");
                }
                return this._Tim;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::AirVinyl.Model.PersonSingle _Tim;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""AirVinyl.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Person"">
        <Key>
          <PropertyRef Name=""PersonId"" />
        </Key>
        <Property Name=""PersonId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""FirstName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""LastName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""DateOfBirth"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Gender"" Type=""AirVinyl.Model.Gender"" Nullable=""false"" />
        <Property Name=""NumberOfRecordsOnWishList"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AmountOfCashToSpend"" Type=""Edm.Decimal"" Nullable=""false"" />
        <NavigationProperty Name=""Friends"" Type=""Collection(AirVinyl.Model.Person)"" />
        <NavigationProperty Name=""VinylRecords"" Type=""Collection(AirVinyl.Model.VinylRecord)"" ContainsTarget=""true"" />
      </EntityType>
      <EntityType Name=""RecordStore"">
        <Key>
          <PropertyRef Name=""RecordStoreId"" />
        </Key>
        <Property Name=""RecordStoreId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""StoreAddress"" Type=""AirVinyl.Model.Address"" />
        <Property Name=""Tags"" Type=""Collection(Edm.String)"" />
        <Property Name=""TagsAsString"" Type=""Edm.String"" />
        <NavigationProperty Name=""Ratings"" Type=""Collection(AirVinyl.Model.Rating)"" />
      </EntityType>
      <EntityType Name=""VinylRecord"" OpenType=""true"">
        <Key>
          <PropertyRef Name=""VinylRecordId"" />
        </Key>
        <Property Name=""VinylRecordId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Title"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Artist"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""CatalogNumber"" Type=""Edm.String"" />
        <Property Name=""Year"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""PressingDetail"" Type=""AirVinyl.Model.PressingDetail"" />
        <NavigationProperty Name=""Person"" Type=""AirVinyl.Model.Person"" />
        <NavigationProperty Name=""DynamicVinylRecordProperties"" Type=""Collection(AirVinyl.Model.DynamicProperty)"" />
      </EntityType>
      <EntityType Name=""PressingDetail"">
        <Key>
          <PropertyRef Name=""PressingDetailId"" />
        </Key>
        <Property Name=""PressingDetailId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Grams"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Inches"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""DynamicProperty"">
        <Key>
          <PropertyRef Name=""Key"" />
          <PropertyRef Name=""VinylRecordId"" />
        </Key>
        <Property Name=""Key"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""SerializedValue"" Type=""Edm.String"" />
        <Property Name=""VinylRecordId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""VinylRecord"" Type=""AirVinyl.Model.VinylRecord"">
          <ReferentialConstraint Property=""VinylRecordId"" ReferencedProperty=""VinylRecordId"" />
        </NavigationProperty>
      </EntityType>
      <ComplexType Name=""Address"">
        <Property Name=""Street"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Edm.String"" />
        <Property Name=""PostalCode"" Type=""Edm.String"" />
        <Property Name=""Country"" Type=""Edm.String"" />
      </ComplexType>
      <EntityType Name=""Rating"">
        <Key>
          <PropertyRef Name=""RatingId"" />
        </Key>
        <Property Name=""RatingId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Value"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""RatedBy"" Type=""AirVinyl.Model.Person"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""SpecializedRecordStore"" BaseType=""AirVinyl.Model.RecordStore"">
        <Property Name=""Specialization"" Type=""Edm.String"" />
      </EntityType>
      <EnumType Name=""Gender"">
        <Member Name=""Female"" Value=""0"" />
        <Member Name=""Male"" Value=""1"" />
        <Member Name=""Other"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""AirVinyl.Functions"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""IsHighRated"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""AirVinyl.Model.RecordStore"" />
        <Parameter Name=""minimumRating"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.Boolean"" Nullable=""false"" />
      </Function>
      <Function Name=""AreRatedBy"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(AirVinyl.Model.RecordStore)"" />
        <Parameter Name=""personIds"" Type=""Collection(Edm.Int32)"" Nullable=""false"" />
        <ReturnType Type=""Collection(AirVinyl.Model.RecordStore)"" />
      </Function>
      <Function Name=""GetHighRatedRecordStores"">
        <Parameter Name=""minimumRating"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Collection(AirVinyl.Model.RecordStore)"" />
      </Function>
    </Schema>
    <Schema Namespace=""AirVinyl.Actions"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""Rate"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""AirVinyl.Model.RecordStore"" />
        <Parameter Name=""rating"" Type=""Edm.Int32"" Nullable=""false"" />
        <Parameter Name=""personId"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.Boolean"" Nullable=""false"" />
      </Action>
      <Action Name=""RemoveRatings"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(AirVinyl.Model.RecordStore)"" />
        <Parameter Name=""personId"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.Boolean"" Nullable=""false"" />
      </Action>
      <Action Name=""RemoveRecordStoreRatings"">
        <Parameter Name=""personId"" Type=""Edm.Int32"" Nullable=""false"" />
      </Action>
    </Schema>
    <Schema Namespace=""AirVinyl"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""AirVinylContainer"">
        <EntitySet Name=""People"" EntityType=""AirVinyl.Model.Person"">
          <NavigationPropertyBinding Path=""Friends"" Target=""People"" />
        </EntitySet>
        <EntitySet Name=""RecordStores"" EntityType=""AirVinyl.Model.RecordStore"" />
        <Singleton Name=""Tim"" Type=""AirVinyl.Model.Person"">
          <NavigationPropertyBinding Path=""Friends"" Target=""People"" />
        </Singleton>
        <FunctionImport Name=""GetHighRatedRecordStores"" Function=""AirVinyl.Functions.GetHighRatedRecordStores"" EntitySet=""RecordStores"" IncludeInServiceDocument=""true"" />
        <ActionImport Name=""RemoveRecordStoreRatings"" Action=""AirVinyl.Actions.RemoveRecordStoreRatings"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for GetHighRatedRecordStores in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceQuery<global::AirVinyl.Model.RecordStore> GetHighRatedRecordStores(int minimumRating)
        {
            return this.CreateFunctionQuery<global::AirVinyl.Model.RecordStore>("", "GetHighRatedRecordStores", false, new global::Microsoft.OData.Client.UriOperationParameter("minimumRating", minimumRating));
        }
        /// <summary>
        /// There are no comments for RemoveRecordStoreRatings in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceActionQuery RemoveRecordStoreRatings(int personId)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery(this, this.BaseUri.OriginalString.Trim('/') + "/RemoveRecordStoreRatings", new global::Microsoft.OData.Client.BodyOperationParameter("personId", personId));
        }
    }
}
